every hour:
  difference between {world_the_end.lastreset} and now is greater than 72 hours:
    broadcast "The End will regenerate in one minute!"
    wait 1 minute
    set {_seed} to random integer between 0 and 4294967295
    execute console command "mv regen world_the_end -s %{_seed}%"
    wait 1 second
    execute console command "mvconfirm"
    set {world_the_end.lastreset} to now
    broadcast "The End has been regenerated. The portal may not work properly for the next few minutes."
